### ISSUE TITLE
Feature Request: Add feature show animated badge

### ISSUE THREAD

**Issue by SanjaySRocks** [KevzPeter/Leetcode-Badge-Showcase#13]
Leetcode graphql gives you user data with the animated gif badge  which can be accessed here

`response.matchedUser.badges[i].medal.config.iconGif`

can you add it so we can toggle between static badge and animated badge.

**Comment by KevzPeter** [comment]
I did implement this a long while back. The reason I stuck with static images is because Vercel (where I've deployed this API) has a max limit of 4Mb for API response sizes. Another thing to note is if the API response takes more than 5 seconds, Github refuses to render the image in the README.MD file.

These are *really* small data and time constraints to play with, since converting the number of badges (png/jpg) for the average user easily exceed these. That's why I've had to convert & compress the response images to WebP image format, and a local caching mechanism to quickly retrieve those images for the badges.

Now, if I were to send GIFs as responses, the output would be > 10Mb and > 30s for image conversion.

So I won't be able to add animated badges (atleast for now) !

**Comment by KevzPeter** [comment]
Nevermind, I found a way to compress GIFs too. To try it out, add a query param like so: `&animated=true`

> eg: `https://leetcode-badge-showcase.vercel.app/api?username={your-username}&animated=true`

![LeetCode Badges](https://leetcode-badge-showcase.vercel.app/api?username=kevzpeter&animated=true&theme=dark&filter=comp)

**Comment by SanjaySRocks** [comment]
> https://leetcode-badge-showcase.vercel.app

Works flawless.
